export { FONTS, type FontFamily } from './fonts';
export { LANGUAGES, VIEWPORTS } from './languages';
export {
  STORAGE_KEY,
  DEFAULT_GLOBAL_BG,
  DEFAULT_AUTH_STYLES,
  DEFAULT_SECTION_STYLES,
  DEFAULT_TEXT_ELEMENT_STYLES,
  DEFAULT_IMAGE_ELEMENT_STYLES,
  DEFAULT_LOCALIZED_CONTENT,
} from './defaults';
